.NET Framework 类库中的所有异常都派生于 Exception 类，异常包括系统异常和应用异常。

默认所有系统异常派生于 System.SystemException，所有的应用程序异常派生于 System.ApplicationException。

常用的异常类示：

<img src="https://raw.githubusercontent.com/wqcblog/picgo-image/master/2022/05/20220519_1652939638.gif" alt="4-1Z402113334504" style="zoom:80%;" />

常用的**系统异常类**如下表所示。

| 异常类                          | 说明                |
| ------------------------------- | ------------------- |
| System.OutOfMemoryException     | 用 new 分配内存失败 |
| System.StackOverflowException   | 递归过多、过深      |
| System.NullReferenceException   | 对象为空            |
| Syetem.IndexOutOfRangeException | 数组越界            |
| System.ArithmaticException      | 算术操作异常的基类  |
| System.DivideByZeroException    | 除零错误            |

## try catch finally：异常处理

异常与异常处理语句包括三种形式，即 try catch、try finally、try catch finally。

在上述三种异常处理的形式中所用到关键字其含义如下：

- try：用于检查发生的异常，并帮助发送任何可能的异常。 
- catch：以控制权更大的方式处理错误，可以有多个 catch 子句。 
- finally：无论是否引发了异常，finally 的代码块都将被执行。

### try catch

在 try 语句中放置可能出现异常的语句，而在 catch 语句中放置异常时处理异常的语句，通常在 catch 语句中输出异常信息或者发送邮件给开发人员等。

另外，在处理异常时，catch 语句是允许多次使用的，相当于多分支的 if 语句，仅能执行其中一个分支。

```cs
public partial class tryCatchForm : Form
{
    public tryCatchForm()
    {
        InitializeComponent();
    }
    //“确认”按钮单击事件
    private void button1_Click(object sender, EventArgs e)
    {
        //获取文本框中的值
        string str = textBox1.Text;
        //将字符串装换为整数
        try
        {
            int num = int.Parse(str);
            MessageBox.Show("您输入的数字是：" + num);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message);
        }
    }
}
```

```cs
class Program
{
    static void Main(string[] args)
    {
        //定义存放5个整数的数组
        int[] a = new int[5];
        try
        {
            for(int i = 0; i < a.Length; i++)
            {
                a[i] = int.Parse(Console.ReadLine());//依次逐个读取(缓存进入)
            }
            for(int i = 0; i < a.Length; i++)
            {
                Console.Write(a[i] + " ");
            }
        }
        catch(FormatException f)
        {
            Console.WriteLine("输入的数字格式不正确！");
        }
        catch(OverflowException o)
        {
            Console.WriteLine("输入的值已经超出 int 类型的最大值！");
        }
        catch(IndexOutOfRangeException r)
        {
            Console.WriteLine("数组越界异常！");
        }
    }
}
```

### try finally

在 try finally 形式中没有单独对出现异常时处理的代码，finally 语句是无论 try 中的语句是否正确执行都会执行的语句。通常在 finally 中编写的代码是关闭流、关闭数据库连接等操作，以免造成资源的浪费。

```cs
public partial class tryCatchForm : Form
{
    public tryCatchForm()
    {
        InitializeComponent();
    }
    //“确认”按钮单击事件
    private void button1_Click(object sender, EventArgs e)
    {
        //获取文本框中的值
        string str = textBox1.Text;
        //将字符串装换为整数
        try
        {
            int num = int.Parse(str);
            MessageBox.Show("您输入的数字是：" + num);
        }
        finally
        {
            MessageBox.Show("finally 语句");
        }
    }
}
```

```cs
public partial class TryFinallyForm : Form
{
    public TryFinallyForm()
    {
        InitializeComponent();
    }
    //"确认"按钮的单击事件
    private void button1_Click(object sender, EventArgs e)
    {
        //获取文本框
        string city = txtCity.Text;
        string msg = txtMsg.Text;
        string min = txtMin.Text;
        string max = txtMax.Text;
        //将文本框中的内容组成一个字符串
        string message = city + "：" + msg + "：" + min + "~" + max;
        //定义文件路径
        string path = "D:\\C#_test\\weather.txt";
        FileStream fileStream = null;
        try
        {
            //创建fileSteam类的对象
            fileStream = new FileStream(path, FileMode.OpenOrCreate);
            //将字符串转换成字节数组
            byte[] bytes = Encoding.UTF8.GetBytes(message);
            //向文件中写入字节数组
            fileStream.Write(bytes, 0, bytes.Length);
            //刷新缓冲区
            fileStream.Flush();
            //弹出录入成功的消息框
            MessageBox.Show("天气信息录入成功！");
        }
        finally
        {
            if (fileStream != null)
            {
                //关闭流
                fileStream.Close();
            }
        }
    }
}
```

### try catch finally

try catch finally 形式语句是使用最多的一种异常处理语句。

在出现异常时能提供相应的异常处理，并能在 finally 语句中保证资源的回收。

```cs
public partial class TryFinallyForm : Form
{
    public TryFinallyForm()
    {
        InitializeComponent();
    }
    //"确认"按钮的单击事件
    private void button1_Click(object sender, EventArgs e)
    {
        //获取文本框
        string city = txtCity.Text;
        string msg = txtMsg.Text;
        string min = txtMin.Text;
        string max = txtMax.Text;
        //将文本框中的内容组成一个字符串
        string message = city + "：" + msg + "：" + min + "~" + max;
        //定义文件路径
        string path = "D:\\C#_test\\weather.txt";
        FileStream fileStream = null;
        try
        {
            //创建fileSteam类的对象
            fileStream = new FileStream(path, FileMode.OpenOrCreate);
            //将字符串转换成字节数组
            byte[] bytes = Encoding.UTF8.GetBytes(message);
            //向文件中写入字节数组
            fileStream.Write(bytes, 0, bytes.Length);
            //刷新缓冲区
            fileStream.Flush();
            //弹出录入成功的消息框
            MessageBox.Show("天气信息录入成功！");
        }
        catch(Exception ex)
        {
            MessageBox.Show("出现错误！" + ex.Message);
        }
        finally
        {
            if (fileStream != null)
            {
                //关闭流
                fileStream.Close();
            }
        }
    }
}
```

## 自定义异常

自定义异常类必须要继承 Exception 类。

声明异常的语句如下。

```cs
class 异常类名 :Exception
{
}
```

抛出自己的异常，语句如下

```cs
throw( 异常类名 );
```

```cs
class MyException :Exception
{
    public MyException(string message) : base(message)//异常类中Message属性设置为传入的message值
    {
    }
}//编写自定义异常类
```

```cs
private void button1_Click(object sender, EventArgs e)
{
    try
    {
        int age = int.Parse(textBox1.Text);
        if (age < 18 || age > 45)
        {
            throw new MyException("年龄必须在18~45岁之间！");
        }
        else
        {
            MessageBox.Show("输入的年龄正确！");
        }
    }
    catch(MyException myException)
    {
        MessageBox.Show(myException.Message);
    }
    catch(Exception ex)
    {
        MessageBox.Show(ex.Message);
    }
}
```

## Debug和Trace

非中断调试显示程序有关的信息。

输出调试信息的类保存在 System.Diagnostics 命名空间中，通常用 Debug 类或 Trace 类实现调试时输出调试信息，具体的语句如下。

```cs
Debug.WriteLine();
Trace.WriteLine();
```

其中，Debug.WriteLine() 是在调试模式下使用的；Trace.WriteLine 除了可以在调试模式下使用，还可以用于发布的程序中。

```cs
class Program
{
    static void Main(string[] args)
    {
        string[] str = new string[5];
        Debug.WriteLine("开始向数组中存值：");
        for(int i = 0; i < str.Length; i++)
        {
            str[i] = Console.ReadLine();
            Debug.WriteLine("存入的第{0}个值为{1}", i, str[i]);
        }
        Debug.WriteLine("向数组中存值结束！");
    }
}
```

使用 Trace 类也能完成同样的效果，只需将上述代码中的 Debug 类换成 Trace 类即可。

>提示：Trace 类的 WriteLine 方法中的参数不支持上述代码中 Debug 类的 WriteLine 方法的参数形式，只能传递字符串(仅能单纯打印字符串)。

当程序在 Debug 状态下执行时使用 Debug 类打印的信息才会在输出窗口中显示，在 Release 状态下执行时只有 Trace 类输出的内容才会显示在输出窗口中。
